/*
 * Generated by erpcgen 1.8.0 on Thu Jan 21 10:51:58 2021.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_pippo_server_h_)
#define _pippo_server_h_

#ifdef __cplusplus
#include "erpc_server.h"
#include "erpc_codec.h"
extern "C"
{
#include "pippo.h"
#include <stdint.h>
#include <stdbool.h>
}

#if 10800 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


/*!
 * @brief Service subclass for pluto.
 */
class pluto_service : public erpc::Service
{
public:
    pluto_service() : Service(kpluto_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for scrivi of pluto interface. */
    erpc_status_t scrivi_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for leggi of pluto interface. */
    erpc_status_t leggi_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#else
#include "pippo.h"
#endif // __cplusplus

typedef void * erpc_service_t;

erpc_service_t create_pluto_service(void);

void destroy_pluto_service(void);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _pippo_server_h_
