/*
 * Generated by erpcgen 1.8.0 on Thu Jan 21 10:51:58 2021.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_pippo_h_)
#define _pippo_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10800 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief pluto identifiers */
enum _pluto_ids
{
    kpluto_service_id = 1,
    kpluto_scrivi_id = 1,
    kpluto_leggi_id = 2,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name pluto
//@{
bool scrivi(uint32_t val);

uint32_t leggi(void);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _pippo_h_
