#
# Generated by erpcgen 1.8.0 on Thu Jan 21 10:20:53 2021.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# Abstract base class for pluto
class Ipluto(object):
    SERVICE_ID = 1
    SCRIVI_ID = 1
    LEGGI_ID = 2

    def scrivi(self, val):
        raise NotImplementedError()

    def leggi(self):
        raise NotImplementedError()


